name: sleek
base: core18
version: '0.7.0'
summary: sleek is a todo app based on todo.txt, free and open-source
description: |
  sleek offers a clean and simple interface that can be used with mouse and keyboard, keyboard only or touch devices. You will use an easy to understand but powerful syntax to create todos. According to the concept of todo.txt you can add contexts to your todos or assign them to projects you're working on. Priorities can be set and if you add due dates sleek will send you notifications just in time.

  All that can be done typing plain text or guided by sleeks interface that for instance will present suggestions on contexts and projects while typing, offers a date picker to ease the selection of due dates or presents a recurrence picker, if your todos should repeat themselves.

  There is no cloud integration, but as sleek writes your todos into a plain text file, you can put it anywhere and sync it to all your devices. That also means if you don't have sleek at hand or if you don't like it any more you can just edit the todo.txt file with any text editor or other todo.txt application.

grade: stable
confinement: strict
icon: ./assets/icons/icon.png
license: MIT
compression: lzo
architectures:
- build-on: [amd64, armhf, arm64, s390x, ppc64el]
  run-on: [amd64, armhf, arm64, s390x, ppc64el]
- build-on: i386
  run-on: i386
apps:
  sleek:
    command: snap/command-chain/desktop-launch $SNAP/sleek/sleek --disable-gpu --no-sandbox
    environment:
      DISABLE_WAYLAND: 1
      TMPDIR: $XDG_RUNTIME_DIR
      PATH: "$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
    extensions: [gnome-3-28]
    plugs:
    - home
    - browser-support
parts:
  sleek:
    plugin: nil
    build-environment:
    - PATH: "$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin"
    build-snaps:
    - node/12/stable
    source: .
    override-build: |
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi
      npm install
      electron-packager . --overwrite --platform=linux --output=release-build \
          --prune=true --out $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/$SNAPCRAFT_PROJECT_NAME-linux-* \
          $SNAPCRAFT_PART_INSTALL/sleek
    stage-packages:
    - libnss3
  cleanup:
    after: [ sleek ]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
      set -eux
      for snap in "gnome-3-28-1804"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
