name: Code scan, update Flathub and mirror to opencode.net
on:
  push:
    branches:
      - '*'
jobs:
  trigger-flathub_build:
    name: Update commit id in Flathub repo
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Flathub build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TRIGGER_FLATHUB_BUILD }}
          repository: ransome1/com.github.ransome1.sleek
          event-type: trigger-flathub-build
          client-payload: '{"commit_id": "${{ github.sha }}"}'  
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  njsscan:
    needs: snyk
    name: njsscan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
  # codecov:
  #   needs: njsscan
  #   name: Codecov
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       language: ['javascript']
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@master
  #     - name: Set up latest available Nodejs
  #       uses: actions/setup-node@master
  #     - name: Install dependencies
  #       run: yarn install
  #     - name: Build
  #       run: yarn build
  #     - name: Run tests
  #       run: yarn run test
  #     - name: Upload coverage reports to Codecov
  #       uses: codecov/codecov-action@v4
  #       env:
  #         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  codeql:
    needs: njsscan
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up latest available Nodejs
        uses: actions/setup-node@master
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  mirror:
    name: Mirror code to opencode.net
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: https://www.opencode.net/ransome/sleek.git
          username: ransome
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
