name: Build & release
on:
  push:
    tags:
      - '*'
jobs:
  macos:
    name: MacOS (Build & Release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build
      - name: Run Electron Builder
        uses: samuelmeuli/action-electron-builder@v1
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLEID: ${{ secrets.APPLE_ID }}
          APPLEIDPASS: ${{ secrets.APPLE_ID_PASS }}
        with:
          max_attempts: 3
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
  windows:
    name: Windows (Build & Release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build
      - name: Run Electron Builder
        uses: samuelmeuli/action-electron-builder@v1
        with:
          max_attempts: 3
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
  linux:
    name: Linux (Build & Release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build
      - name: Run Electron Builder
        uses: samuelmeuli/action-electron-builder@v1
        with:
          max_attempts: 3
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}