name: Prepare releases
on:
  push:
    tags:
      - '*'
jobs:
  macos:
    name: MacOS (Prepare release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@master
      - name: Install Node and NPM
        uses: actions/setup-node@master
        with:
          node-version: 23
          cache: 'yarn'
      - name: Install and build
        run: |
          yarn --network-timeout 100000
          yarn run build
      - name: Run Electron Builder
        uses: samuelmeuli/action-electron-builder@v1
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          DEBUG: ${{ secrets.DEBUG }}
        with:
          max_attempts: 5
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
  windows:
    name: Windows (Prepare release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@master
      - name: Install Node and NPM
        uses: actions/setup-node@master
        with:
          node-version: 23
          cache: 'yarn'
      - name: Install and build
        run: |
          yarn --network-timeout 100000
          yarn run build
      - name: Run Electron Builder
        uses: samuelmeuli/action-electron-builder@v1
        env:
          DEBUG: ${{ secrets.DEBUG }}
        with:
          max_attempts: 5
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
  linux:
    name: Linux (Prepare release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@master
      - name: Install Node and NPM
        uses: actions/setup-node@master
        with:
          node-version: 23
          cache: 'yarn'
      - name: Install and build
        run: |
          yarn --network-timeout 100000
          yarn run build
      - name: Run Electron Builder
        uses: samuelmeuli/action-electron-builder@v1
        env:
          DEBUG: ${{ secrets.DEBUG }}
        with:
          max_attempts: 5
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
