name: Prepare releases
on:
  push:
    tags:
      - '*'
jobs:
  trigger-flathub_build:
    name: Trigger Flathub build bot
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Flathub build
      uses: peter-evans/repository-dispatch@v2.1.2
      with:
        token: ${{ secrets.TRIGGER_FLATHUB_BUILD }}
        repository: ransome1/com.github.ransome1.sleek
        event-type: trigger-flathub-build
        client-payload: '{"commit_id": "${{ github.sha }}"}'  
  macos:
    name: MacOS (Prepare release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install and build
        run: |
          yarn --network-timeout 100000
          yarn run build
      - name: Run Electron Builder
        uses: coparse-inc/action-electron-builder@v1.0.0
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
        with:
          max_attempts: 5
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
  windows:
    name: Windows (Prepare release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install and build
        run: |
          yarn --network-timeout 100000
          yarn run build
      - name: Run Electron Builder
        uses: coparse-inc/action-electron-builder@v1.0.0
        with:
          max_attempts: 5
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
  linux:
    name: Linux (Prepare release)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install and build
        run: |
          yarn --network-timeout 100000
          yarn run build
      - name: Run Electron Builder
        uses: coparse-inc/action-electron-builder@v1.0.0
        with:
          max_attempts: 5
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}