name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Commit and push to flathub to trigger build process
        run: |
          git remote set-url --push origin git@github.com:flathub/com.github.ransome1.sleek.git
          git commit --allow-empty -m "Build"
          git push
